apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  DATABASE_URL: "your_DB_URL"
  DJANGO_SUPERUSER_PASSWORD: "your_password"
  DJANGO_SECRET_KEY: "your_secretkey"
  DEBUG: "Off"
