apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  labels:
    name: django-ingress
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - pathType: Prefix
        path: "/api/books"
        backend:
          service:
            name: django-svc
            port: 
              number: 8000